# Generated by Django 2.0.1 on 2021-06-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('color', models.CharField(max_length=30)),
            ],
        ),
    ]
