# Generated by Django 2.0.1 on 2021-06-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='position',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
    ]
